FROM  node:20-bullseye

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# ACCESS PORT
ENV PORT=5001

# DATABASE
ENV DB_HOST=localhost
ENV DB_USER=postgres
ENV DB_PORT=5432
ENV DB_PASSWORD=kimaru
ENV DB_NAME=school

# AUTHENTICATION
ENV JWT_ACCESS_TOKEN_SECRET_KEY=GLUIEFiTgn8biybc1q7NoXBy/7XItzhe6FfSdC+gVnQ=
ENV JWT_REFRESH_TOKEN_SECRET_KEY=eO2UBC3WGZNxX60KXl7okKFeolP554mLfRYCCcbgMxU=

# SMS VARIABLES
ENV TEXT_SMS_API_BASE_URL=https://sms.textsms.co.ke/api/services
ENV TEXTSMS_API_KEY=86d11a3637ee30e5714c6457fdbf7d91
ENV TEXTSMS_PARTNER_ID=12541
ENV TEXTSMS_SHORTCODE=TextSMS

#DEV / PRODUCTIONS ENV
ENV NODE_ENV=dev

ENV NODE_DOMAIN=.onrender.com

# FRONTEND BASE URL
ENV BACKEND_BASE_URL=http://localhost:5001
ENV FRONTEND_BASE_URL=http://localhost:5173


EXPOSE 5001

CMD ["npm", "start"]
